services:
  frontend:
    build:
      context: ./
      dockerfile: client.Dockerfile
    ports: 
      - 5000:5000
    container_name: client

  server:
    build:
      context: ./
      dockerfile: server.Dockerfile
    ports: 
      - 8080:8080
    container_name: server
