services:
  client:
    build:
      context: ./
      dockerfile: client.Dockerfile
    ports: 
      - 5000:5000
    container_name: client

  server:
    build:
      context: ./
      dockerfile: server.Dockerfile
    ports: 
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
    container_name: server

  redis:
    image: redis:latest
    ports: 
      - 6379:6379
    container_name: redis

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - database:/var/lib/postgresql/data
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080

  reverse_proxy:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "80:80"
    environment:
    - NGINX_PORT=80
    

volumes:
  database:
  files:

